name: flutter_base_example
description: Demonstrates how to use the flutter_base plugin.
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.4.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.5
  cached_network_image: 3.2.2

  flutter_base:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:

  uses-material-design: true
