name: flutter_base
description: A new base Flutter project.
version: 1.5.0
author: archko
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.4
  json_annotation: 4.3.0

  dio: 4.0.1
  pull_to_refresh: 2.0.0

  #isolate: ^2.0.3

  provider: 6.0.1
  #webview_flutter: ^0.3.19+5
  flutter_webview_plugin: 0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: 6.0.1

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  plugin:
    androidPackage: cn.archko.flutter.base.flutter_base
    pluginClass: FlutterBasePlugin
